# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# See https://pants.readme.io/docs/using-pants-in-ci for tips on how to set up your CI with Pants.

env:
  global:
    - PANTS_CONFIG_FILES=pants.ci.toml

os: linux
dist: bionic
language: python
python:
  - 3.7
  - 3.8

cache:
  directories:
    - $HOME/.cache/pants/setup
    - $HOME/.cache/pants/lmdb_store

install:
  - ./pants --version  # This will bootstrap Pants

script:
  - ./pants lint '::'  # these need quoting for travis
  - mkdir -p dist/ # needed for coverage/xunit output
  - ./pants test '::'
  - ./pants binary '::'
  - ./pants setup-py --args="bdist_wheel" '::'

