


python_tests(
    # name defaults to the name of the directory the BUILD file is in `tests`
    # sources defaults to ['*_test.py', 'test_*.py', 'conftest.py'].
    dependencies = [
        "src/python/library_project1/src:library1",
    ]
)