

python_tests(
    name = 'tests',
    # sources defaults to ['*_test.py', 'test_*.py', 'conftest.py'].
    # sources = [
    #     'tests/**/test_*.py',
    #     'tests/**/conftest.py',
    # ],
    dependencies = [
        "src/python/project1/src/project1",
    ]
)