
python_binary(
    # name defaults to the name of this directory, i.e., `library1`.
    # sources defaults to ['*.py', '!*_test.py', '!test_*.py', '!conftest.py'].
    sources = ["cli.py"],
    entry_point = 'project1.cli',
    dependencies = [
        'src/python/library1',
    ],
)

